version: '3.3'

services:
  frontend:
    container_name: dashboard
    build:
      context: frontend/
      dockerfile: Dockerfile
    image: ds21m026/frontend
    command: 
      "streamlit run streamlit.py --server.port 8501"
    ports:
      - "8501:8501"
    networks:
      - default
      
  backend:
    container_name: model_api
    build:
      context: backend/
      dockerfile: Dockerfile
    image: ds21m026/backend
    ports:
      - "8000:8000"
    networks:
      - default
  
networks:
  default:
